apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-04-21T17:44:25Z
  generation: 1
  labels:
    app: demo
    chart: demo-0.1.0
    heritage: Tiller
    release: r1
  name: r1-demo
  namespace: default
  resourceVersion: "31027"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/r1-demo
  uid: a232ac47-458b-11e8-9b53-025000000001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      release: r1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
        release: r1
    spec:
      containers:
      - image: oleg
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  containers:
  - image: oleg
  templates:
    containers:
    - image: oleg
    spec:
      containers:
      - image: oleg
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-04-21T17:44:25Z
    lastUpdateTime: 2018-04-21T17:44:25Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1